# Generated by Django 2.1.8 on 2021-05-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedLangCenter_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_post', models.TextField(blank=True, max_length=300, null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
