# Generated by Django 2.1.8 on 2021-05-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedLangCenter_website', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
