# Generated by Django 2.1.8 on 2021-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedLangCenter_website', '0005_auto_20210517_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='mail',
            field=models.EmailField(default='franklynkennedy@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
