# Generated by Django 2.1.8 on 2021-05-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedLangCenter_website', '0007_feedback_feedback_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contents',
            new_name='Content',
        ),
    ]
