# Generated by Django 2.1.8 on 2021-05-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedLangCenter_website', '0010_auto_20210518_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='business_days',
            field=models.TextField(max_length=500),
        ),
    ]
